name: VyOS v1.4 LTS Release
permissions:
  contents: write
on:
  push:
    tags: [ '1.4.*' ]

env:
  GIT_CLONE_URL: https://github.com/vyos/vyos-build
  ARCHITECTURE: amd64
  BUILD_BY: vyos-build-action@github.com
  BUILD_TYPE: release
  DEBIAN_MIRROR: http://ftp.us.debian.org/debian/

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: vyos/vyos-build:sagitta
      options: --workdir /vyos --privileged

    steps:
      - name: Clone source code
        run: git clone --depth 1 -b $GITHUB_REF_NAME --single-branch $GIT_CLONE_URL

      - name: Build ISO
        working-directory: ./vyos-build
        run: |
          sudo make clean
          sudo ./build-vyos-image iso --architecture $ARCHITECTURE --build-by $BUILD_BY --build-type $BUILD_TYPE --version $GITHUB_REF_NAME

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: vyos-${{ github.ref_name }}-${{ env.ARCHITECTURE }}-iso
          path: vyos-build/build/vyos-${{ github.ref_name }}-*.iso

  release:
    permissions: write-all
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: vyos-${{ github.ref_name }}-${{ env.ARCHITECTURE }}-iso

    - name: Create tag
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/${{ github.ref_name }}',
            sha: context.sha
          })

    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: VyOS v${{ env.BUILD_VERSION }}
        body: VyOS v${{ env.BUILD_VERSION }}
        draft: false
        prerelease: false
        files: |
          vyos-${{ github.ref_name }}-${{ env.ARCHITECTURE }}.iso
